wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667796650.774793
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 120
epochs:
  desc: null
  value: 30
hight:
  desc: null
  value: 180
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: rmsprop
width:
  desc: null
  value: 180
